title: Pink Pigeon CMS
lang: en
description: This is the documentation for the Pink Pigeon CMS

remote_theme: pinkpigeondocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
