title: Pink Pigeon
lang: en
description: This is the documentation for the Pink Pigeon Website Builder & CMS

remote_theme: pinkpigeondocs/pp_docs_theme

debug:
  compress: false

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock

google:
  gtag: G-YH5CH80ZEP
